import burp.api.montoya.MontoyaApi;

import javax.swing.*;

/**
 *
 * Original @author lor
 * Modified by Theron Hawley
 */
public class BurpTab extends javax.swing.JPanel {

    private static final String SETTINGS_KEY = "BetterHeader.settings.";
    /**
     * Creates new form BurpTab
     */
    public BurpTab(MontoyaApi api) {
        initComponents(api);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents(MontoyaApi api) {


        buttonGroup1 = new javax.swing.ButtonGroup();
        headerValueLabel = new javax.swing.JLabel();
        headerNameLabel = new javax.swing.JLabel();
        headerValuePrefixText = new javax.swing.JTextField();
        headerValuePrefixLabel = new javax.swing.JLabel();
        headerNameText = new javax.swing.JTextField();
        finalResultLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        hardCodedText = new javax.swing.JTextArea();
        updatePreviewButton = new javax.swing.JButton();
        regExpRadio = new javax.swing.JRadioButton();
        hardCodedRadio = new javax.swing.JRadioButton();
        regExpText = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        addbox = new JCheckBox();
        replacebox = new JCheckBox();

        addbox.setText("Add header");
        addbox.setSelected( api.persistence().preferences().getBoolean(SETTINGS_KEY+"IsAdding"));
        replacebox.setText("Replace header");
        replacebox.setSelected( api.persistence().preferences().getBoolean(SETTINGS_KEY+"IsReplacing"));

        headerValueLabel.setText("Header value");

        headerNameLabel.setText("Header name");

        headerValuePrefixText.setText(api.persistence().preferences().getString(SETTINGS_KEY+"HeaderPrefix"));
        headerValuePrefixText.setToolTipText("Don't forget the space");
        //headerValuePrefixText.addActionListener(evt -> api.persistence().preferences().setString(BurpTab.SETTINGS_KEY+"HeaderPrefix", headerValuePrefixText.getText()));

        headerValuePrefixLabel.setText("Header value (prefix)");

        headerNameText.setText(api.persistence().preferences().getString(SETTINGS_KEY+"HeaderName"));
        //headerNameText.addActionListener(evt -> api.persistence().preferences().setString(BurpTab.SETTINGS_KEY+"HeaderName", headerNameText.getText()));

        finalResultLabel.setText("The new header will look like this");
        finalResultLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        hardCodedText.setColumns(20);
        hardCodedText.setRows(5);
        hardCodedText.setText(api.persistence().preferences().getString(SETTINGS_KEY+"HardcodedText"));
        //hardCodedText.getDocument().addDocumentListener(new HCDocumentListener());
        jScrollPane1.setViewportView(hardCodedText);
        //jScrollPane1.addPropertyChangeListener("ViewportView", e -> api.persistence().preferences().setString(SETTINGS_KEY+"HardcodedText",hardCodedText.getText()));

        updatePreviewButton.setText("Update Header");
        updatePreviewButton.addActionListener(evt -> {
            //updatePreviewButtonActionPerformed(evt, api);
            updateFinalResultLabel(api);
        });

        buttonGroup1.add(regExpRadio);
        regExpRadio.setText("Regular Expression");
        //api.logging().logToOutput(api.persistence().preferences().getBoolean(SETTINGS_KEY+"IsRegex").toString());
        //if(api.persistence().preferences().getBoolean(SETTINGS_KEY+"IsRegex")) regExpRadio.setSelected(true);
        //regExpRadio.addActionListener(evt -> api.persistence().preferences().setBoolean(SETTINGS_KEY+"IsRegex", regExpRadio.isSelected()));

        buttonGroup1.add(hardCodedRadio);
        hardCodedRadio.setText("Hard-Coded Value");
        //if(api.persistence().preferences().getBoolean(SETTINGS_KEY+"IsHardcoded")) regExpRadio.setSelected(true);
        //hardCodedRadio.addActionListener(evt -> api.persistence().preferences().setBoolean(SETTINGS_KEY+"IsHardcoded", hardCodedRadio.isSelected()));

        regExpText.setText(api.persistence().preferences().getString(SETTINGS_KEY+"RegexText"));
        //regExpText.addActionListener(evt -> api.persistence().preferences().setString(SETTINGS_KEY+"RegexText", regExpText.getText()));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE)
        );

        buttonGroup1.add(jRadioButton1);
        //jRadioButton1.setSelected(!api.persistence().preferences().getBoolean(SETTINGS_KEY + "IsRegex") && !api.persistence().preferences().getBoolean(SETTINGS_KEY + "IsHardcoded"));
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Disable custom header");
        //jRadioButton1.addActionListener(evt -> {
            ///api.persistence().preferences().setBoolean(SETTINGS_KEY+"IsRegex", false);
            //api.persistence().preferences().setBoolean(SETTINGS_KEY+"IsHardcoded", false);
        //});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(headerValueLabel)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(headerValuePrefixLabel)
                                                        .addComponent(headerNameLabel))
                                                .addGap(44, 44, 44)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(headerNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(headerValuePrefixText, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(199, 199, 199)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(updatePreviewButton)
                                                                .addGap(44, 44, 44))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(addbox)
                                                                        .addComponent(hardCodedRadio)
                                                                        .addComponent(regExpRadio)
                                                                        .addComponent(jRadioButton1))
                                                                .addGap(18, 18, 18)))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(finalResultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 1432, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(replacebox)
                                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(regExpText, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(headerNameLabel)
                                                        .addComponent(headerNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(headerValuePrefixLabel)
                                                        .addComponent(headerValuePrefixText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addComponent(headerValueLabel))
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(regExpRadio)
                                        .addComponent(regExpText, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(hardCodedRadio))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(9, 9, 9)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(addbox)
                                        .addComponent(replacebox))
                                .addGap(21, 21, 21)

                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(updatePreviewButton)
                                        .addComponent(finalResultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(45, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
/*
    private void headerNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_headerNameTextActionPerformed
        updateFinalResultLabel();
    }//GEN-LAST:event_headerNameTextActionPerformed

    private void headerValuePrefixTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_headerValuePrefixTextActionPerformed
        updateFinalResultLabel();
    }//GEN-LAST:event_headerValuePrefixTextActionPerformed

    private void updatePreviewButtonActionPerformed(java.awt.event.ActionEvent evt, MontoyaApi api) {//GEN-FIRST:event_updatePreviewButtonActionPerformed
        updateFinalResultLabel(api);
    }//GEN-LAST:event_updatePreviewButtonActionPerformed

    private void regExpRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regExpRadioActionPerformed

    }//GEN-LAST:event_regExpRadioActionPerformed

    private void regExpTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regExpTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regExpTextActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed
*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel finalResultLabel;
    private javax.swing.JRadioButton hardCodedRadio;
    javax.swing.JTextArea hardCodedText;
    private javax.swing.JLabel headerNameLabel;
    javax.swing.JTextField headerNameText;
    private javax.swing.JLabel headerValueLabel;
    private javax.swing.JLabel headerValuePrefixLabel;
    javax.swing.JTextField headerValuePrefixText;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton regExpRadio;
    private javax.swing.JTextField regExpText;
    private javax.swing.JButton updatePreviewButton;
    private javax.swing.JCheckBox addbox;
    private javax.swing.JCheckBox replacebox;
    // End of variables declaration//GEN-END:variables
/*
    void setHeaderName(String text) {
        headerNameText.setText(text);
    }

    String getHeaderName() {
        return headerNameText.getText();
    }

    void setHeaderValuePrefix(String text) {
        headerValuePrefixText.setText(text);
    }

    String getHeaderValuePrefix() {
        return headerValuePrefixText.getText();
    }

    public boolean useHardCoded() {
        return hardCodedRadio.isSelected();
    }

    public boolean useRegExp() {
        return regExpRadio.isSelected();
    }

    void setHardCodedText(String text) {
        hardCodedText.setText(text);
    }

    String getHardCodedText() {
        return hardCodedText.getText();
    }

    public String getRegExpText() {
        return regExpText.getText();
    }

    public void setRegExpText(String regExpText) {
        this.regExpText.setText(regExpText);
    }
*/
    // custom code
    void updateFinalResultLabel(MontoyaApi api) {

        api.persistence().preferences().setBoolean(SETTINGS_KEY+"init", true);
        api.persistence().preferences().setBoolean(SETTINGS_KEY+"IsRegex", regExpRadio.isSelected());
        api.persistence().preferences().setBoolean(SETTINGS_KEY+"IsHardcoded", hardCodedRadio.isSelected());
        api.persistence().preferences().setString(SETTINGS_KEY+"RegexText", regExpText.getText());
        api.persistence().preferences().setString(SETTINGS_KEY+"HardcodedText",hardCodedText.getText());
        api.persistence().preferences().setString(BurpTab.SETTINGS_KEY+"HeaderName", headerNameText.getText());
        api.persistence().preferences().setString(BurpTab.SETTINGS_KEY+"HeaderPrefix", headerValuePrefixText.getText());
        api.persistence().preferences().setBoolean(SETTINGS_KEY+"IsAdding", addbox.isSelected());
        api.persistence().preferences().setBoolean(SETTINGS_KEY+"IsReplacing", replacebox.isSelected());

        api.logging().logToOutput("init="+api.persistence().preferences().getBoolean(SETTINGS_KEY+"init").toString());
        api.logging().logToOutput("IsRegex="+api.persistence().preferences().getBoolean(SETTINGS_KEY+"IsRegex").toString());
        api.logging().logToOutput("IsHardcoded="+api.persistence().preferences().getBoolean(SETTINGS_KEY+"IsHardcoded").toString());
        api.logging().logToOutput("Regextext="+api.persistence().preferences().getString(SETTINGS_KEY+"RegexText"));
        api.logging().logToOutput("Hardcodedtext="+api.persistence().preferences().getString(SETTINGS_KEY+"HardcodedText"));
        api.logging().logToOutput("headername="+api.persistence().preferences().getString(BurpTab.SETTINGS_KEY+"HeaderName"));
        api.logging().logToOutput("headerprefix="+api.persistence().preferences().getString(BurpTab.SETTINGS_KEY+"HeaderPrefix"));
        api.logging().logToOutput("IsAdding="+api.persistence().preferences().getBoolean(SETTINGS_KEY+"IsAdding").toString());
        api.logging().logToOutput("IsReplacing="+api.persistence().preferences().getBoolean(SETTINGS_KEY+"IsReplacing").toString());

        String finalText = headerNameText.getText() + ": " + headerValuePrefixText.getText();
        if ( hardCodedRadio.isSelected() ) {
            if (hardCodedText.getText().length() < 30) {
                finalText += hardCodedText.getText();
            }else{
                finalText += hardCodedText.getText().substring(0,30)+"...";
            }
        }
        else if ( regExpRadio.isSelected()) {
            finalText += "[regular expression: " + regExpText.getText() + " ]";
        }
        else {
            finalText = "Extension currently disabled.";
        }

        if (addbox.isSelected() && replacebox.isSelected() && !jRadioButton1.isSelected()) {
            finalResultLabel.setText("The header \""+ finalText+ "\" will be added or replaced in all requests");
        }
        else if (addbox.isSelected() && !jRadioButton1.isSelected()){
            finalResultLabel.setText("The header \""+ finalText+ "\" will be added to requests that don't have the "+ headerNameText.getText() + " header.");
        }
        else if (replacebox.isSelected() && !jRadioButton1.isSelected()) {
            finalResultLabel.setText("The header \""+finalText+"\" will replace the "+ headerNameText.getText() + " header in any requests that have it.");
        }
        else finalResultLabel.setText(finalText);

    }

}